### ISSUE TITLE
visual bug iOS - filled rect for each character

### ISSUE THREAD

**Issue by paul-ferragut** [armadillu/ofxFontStash#16]
![rect](https://cloud.githubusercontent.com/assets/904819/6667529/99b43126-cbe4-11e4-85e2-7d5e0b50f427.png)
I got this bug on a page using video and on other page using alpha blending, it works fine in the rest of my app.
I am using the iOS 64bits branch https://github.com/danoli3/openFrameworks/tree/Apothecary/0.9.0-All

**Comment by paul-ferragut** [comment]
the bug disappeared after commenting disableAlphaBlending() before drawing the font

**Comment by armadillu** [comment]
you, you need alpha blending; it uses alpha masked textures to draw each letter
